apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-monitor-sa
  {{- if .Values.serviceAccountRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountRoleArn }}
  {{- end }}
automountServiceAccountToken: false