apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-monitor-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::703440311746:role/s3-monitor-irsa-role"
automountServiceAccountToken: false

